# Gathering facts from all hosts
- hosts: "all"

- hosts: "{{ host_group }}"
  vars:
  become: true
  tasks:
    - name: "make softnet.sh for easier softnet evaluation"
      template:
        src: "templates/softnet.sh.j2"
        dest: "/tmp/softnet.sh"
        mode: 0644

    - name: "backup current /etc/systctl.conf"
      copy:
       src: "/etc/sysctl.conf"
       dest: "/etc/sysctl.conf-{{ansible_date_time.iso8601 }}"
       remote_src: yes

    - name: "configure the new sysctl.conf"
      template:
        src: "templates/sysctl.conf.j2"
        dest: "/etc/sysctl.conf"
        mode: 0644

    - name: "apply sysctl settings with sysctl -p"
      shell: "sysctl -p"