# Gathering facts from all hosts
- hosts: "all"

- hosts: "{{ host_group }}"
  vars:
    yum_mirror_base_url: "http://{{ hostvars[groups['bootstraps'][0]]['ansible_default_ipv4']['address'] }}:8085"
  #remote_user: centos
  become: true
  tasks:
    - name: "install yum.conf"
      copy:
        dest: "/etc/yum.conf"
        content: |
          [main]
          releasever='7.5.1804'
          cachedir=/var/cache/yum/$basearch/$releasever
          keepcache=0
          debuglevel=2
          logfile=/var/log/yum.log
          exactarch=1
          obsoletes=1
          gpgcheck=1
          plugins=1
          installonly_limit=5
          bugtracker_url=http://bugs.centos.org/set_project.php?project_id=23&ref=http://bugs.centos.org/bug_report_page.php?category=yum
          distroverpkg=centos-release
          #  This is the default, if you make this bigger yum won't see if the metadata
          # is newer on the remote and so you'll "gain" the bandwidth of not having to
          # download the new metadata and "pay" for it by yum not having correct
          # information.
          #  It is esp. important, to have correct metadata, for distributions like
          # Fedora which don't keep old packages around. If you don't like this checking
          # interupting your command line usage, it's much better to have something
          # manually check the metadata once an hour (yum-updatesd will do this).
          # metadata_expire=90m
          # PUT YOUR REPOS HERE OR IN separate files named file.repo
          # in /etc/yum.repos.d
          ip_resolve=4
          timeout=3
          retries=2
          exclude=kernel* centos* initscripts* ibutils-libs* docker*

    - name: "make sure old_repos sub-folder exists"
      file:
        path: "/etc/yum.repos.d/old_repos"
        state: directory

    - name: "are repos configured"
      find:
        paths: "/etc/yum.repos.d/"
        patterns: "*.repo"
      register: repos_configured

    - name: "move .repo files to old repos"
      shell: "mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/old_repos"
      when: (repos_configured.files is defined) and (repos_configured.files|length>0)

    - name: "write out local /etc/yum.repos.d/local-repos.repo"
      template:
        src: "templates/local-repos.repo.j2"
        dest: "/etc/yum.repos.d/local-repos.repo"
        mode: 0644

    - name: "clear yum cache and show yum repolist"
      shell: "{{ item }}"
      loop: ["yum clean all","yum repolist -v"]